import type { ServiceCardData } from "@/components/marketplace/service-card";

export const MOCK_SERVICES: ServiceCardData[] = [
  {
    id: "svc-001",
    slug: "mayfair-catering-co",
    title: "Mayfair Catering Co. — Fine Dining Events",
    description:
      "Premium catering for weddings and corporate events. Seasonal British menus, live carving stations, and white-glove service. Trusted by Kensington Palace Hotel.",
    category: "Catering",
    categoryColor: "warning",
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80",
    price: 95,
    originalPrice: 120,
    priceLabel: "Starting from",
    priceUnit: "per head",
    rating: 4.8,
    reviewCount: 312,
    location: "Mayfair",
    city: "London",
    featured: true,
    instantBook: true,
    supplier: {
      name: "James Hartley",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
      verified: true,
    },
  },
  {
    id: "svc-002",
    slug: "lumina-photography-london",
    title: "Lumina Photography & Cinematography",
    description:
      "Award-winning wedding and event photography studio. Candid, editorial, and drone coverage with same-week album delivery.",
    category: "Photography",
    categoryColor: "violet",
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80",
    price: 1800,
    priceLabel: "Full day from",
    priceUnit: "per event",
    rating: 4.9,
    reviewCount: 187,
    location: "Shoreditch",
    city: "London",
    featured: true,
    supplier: {
      name: "Sophie Clarke",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie",
      verified: true,
    },
  },
  {
    id: "svc-003",
    slug: "bloom-floral-studio-london",
    title: "Bloom — Luxury Floral Installations",
    description:
      "Bespoke floral design studio crafting immersive installations for weddings, brand activations, and corporate galas across London.",
    category: "Décor",
    categoryColor: "success",
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800&q=80",
    price: 3500,
    originalPrice: 4800,
    priceLabel: "Package from",
    priceUnit: "per event",
    rating: 4.7,
    reviewCount: 94,
    location: "Notting Hill",
    city: "London",
    newListing: true,
    supplier: {
      name: "Amelia Brooks",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amelia",
      verified: true,
    },
  },
  {
    id: "svc-004",
    slug: "soundwave-av-london",
    title: "SoundWave AV & Intelligent Lighting",
    description:
      "Full-service audio, visual, and intelligent lighting rigs. From intimate Shoreditch gatherings to Wembley-scale productions.",
    category: "AV & Lighting",
    categoryColor: "default",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    price: 1200,
    priceLabel: "Setup from",
    priceUnit: "per day",
    rating: 4.6,
    reviewCount: 256,
    location: "Hackney",
    city: "London",
    instantBook: true,
    supplier: {
      name: "Oliver Nash",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=oliver",
      verified: false,
    },
  },
  {
    id: "svc-005",
    slug: "the-grand-marquee-london",
    title: "The Grand Marquee — Venue Hire",
    description:
      "A stunning 5,000 sq ft climate-controlled marquee venue with modular layouts, rooftop terrace, and in-house AV in the heart of Canary Wharf.",
    category: "Venue",
    categoryColor: "secondary",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
    price: 8500,
    priceLabel: "Hire from",
    priceUnit: "per day",
    rating: 4.5,
    reviewCount: 73,
    location: "Canary Wharf",
    city: "London",
    supplier: {
      name: "Charlotte Webb",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=charlotte",
      verified: true,
    },
  },
  {
    id: "svc-006",
    slug: "sugarcraft-studio-london",
    title: "Sugarcraft Studio — Artisan Cakes",
    description:
      "Custom sculpted cakes, dessert tables, and sugar art for milestone celebrations. A favourite of London's top wedding planners.",
    category: "Bakery",
    categoryColor: "warning",
    image: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800&q=80",
    price: 380,
    originalPrice: 450,
    priceLabel: "3-tier from",
    priceUnit: "per cake",
    rating: 5.0,
    reviewCount: 41,
    location: "Chelsea",
    city: "London",
    newListing: true,
    instantBook: true,
    supplier: {
      name: "Isabella Moore",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=isabella",
      verified: true,
    },
  },
];
